Update release trigger to allow workflow dispatch
dappnode/DAppNodePackage-nethermind-xdai pull request #86
Opened 2023-03-17 18:23 UTC by cbermudez97

2023-03-20 08:41 UTC, pablomendezroyo requested changes
Shouldnt the release workflow has as previous job the build test workflow so it only releases if the build suceeds?

2023-03-20 16:15 UTC, cbermudez97 commented
The workflows were split. Previously it only tested when making pull requests to main and build on merge, this was done with a if condition per job. I created two files instead to have the triggers more clear. See the checks for the build test.

2023-03-22 09:36 UTC, pablomendezroyo commented
> The jobs were split. Previously it only tested when making pull requests to main and build on merge, this was done with a if condition per job. I created two files instead to have the triggers more clear. See the checks for the build test.

I agree that the conditions and/or the trigger actions can be modified, however, the release job should only be triggered if the build job has succeeded. Otherwise, it will also fail, so makes sense to have both of them on the same workflow

2023-03-22 09:44 UTC, pablomendezroyo approved these changes

2023-03-22 13:03 UTC, merged